name: Android Custom Build

env:
  backendServiceDefaultUrl: https://api.sandbox.mosip.net
  
on:
  workflow_dispatch:
    inputs:
      backendServiceUrl:
        description: 'Backend service URL'
        required: true
        default: 'https://api.sandbox.mosip.net'
        type: string
      theme:
        description: 'Application Theme'
        required: true
        default: 'orange'
        type: choice
        options:
          - orange
          - purple

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      
      - name: Cache local npm repository
        uses: actions/cache@v3.0.11
        with:
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          path: ~/.npm

      - name: Cache local gradle repository
        uses: actions/cache@v3.0.11
        with:
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper

      - name: Install npm dependencies
        run: |
          npm ci

      - name: Create .env.local file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env.local > android/local.properties

      - name: Setup branch and env
        run: |
          # Strip git ref prefix from version
          echo "BRANCH_NAME=$(echo ${{ github.ref }} | sed -e 's,.*/\(.*\),\1,')" >> $GITHUB_ENV
          echo "GPG_TTY=$(tty)" >> $GITHUB_ENV   

      - name: Setup branch and GPG public key
        run: |
          # Strip git ref prefix from version
          echo ${{ env.BRANCH_NAME }}
          echo ${{ env.GPG_TTY }}

          sudo apt-get --yes install gnupg2
          gpg2 --import ./.github/keys/mosipgpgkey_pub.gpg 
          gpg2 --quiet --batch --passphrase=${{secrets.gpg_secret}}  --allow-secret-key-import --import ./.github/keys/mosipgpgkey_sec.gpg

      - name: Setup Firebase
        run: |
          cd android
          if [ ! -z "$FIREBASE_SECRET" ] && [ -f app/google-services.json.gpg ];then rm -f app/google-services.json;gpg2 --quiet --batch --passphrase=$FIREBASE_SECRET --pinentry-mode loopback --decrypt --output app/google-services.json app/mosip-google-services.json.gpg;fi
        env:
          FIREBASE_SECRET: ${{ secrets.GPG_SECRET }}

      - name: Generate keystore
        run: | 
          echo "$ANDROID_KEYSTORE_FILE" > keystore.jks.b64
          base64 -d -i keystore.jks.b64 > android/app/release.keystore
          echo "storeFile=release.keystore" >> keystore.properties
          echo "keyAlias=androidreleasekey" >> keystore.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> keystore.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> keystore.properties
        env:
          ANDROID_KEYSTORE_FILE: ${{ secrets.INJI_ANDROID_RELEASE_KEYSTORE }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.INJI_ANDROID_RELEASE_KEYPASS }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.INJI_ANDROID_RELEASE_STOREPASS }}

      - name: Export variables for keystore
        run: |
          cd android/app
          export RELEASE_KEYSTORE_ALIAS=androidreleasekey
          export RELEASE_KEYSTORE_PASSWORD=$RELEASE_KEYSTORE_PASSWORD
        env: 
          RELEASE_KEYSTORE_PASSWORD: '${{secrets.INJI_ANDROID_RELEASE_STOREPASS}}'

      - name: Bump version code
        uses: chkfung/android-version-actions@v1.2.1
        with:
          gradlePath: android/app/build.gradle
          versionCode: ${{github.run_number}}

      - name: Create Google Play Config file
        run : |
          cd android
          echo "$INJI_ANDROID_PLAY_STORE_CONFIG_JSON" > play_config.json.b64
          base64 -d -i play_config.json.b64 > play_config.json
        env:
          INJI_ANDROID_PLAY_STORE_CONFIG_JSON: ${{ secrets.INJI_ANDROID_PLAY_STORE_CONFIG_JSON }}

      - name: Run Build
        run: |
          cd android/scripts
          ./run-fastlane.sh
        env:
          MIMOTO_HOST: ${{ github.event.inputs.backendServiceUrl }}
          APPLICATION_THEME: ${{ github.event.inputs.theme }} 
          RELEASE_KEYSTORE_ALIAS: androidreleasekey
          RELEASE_KEYSTORE_PASSWORD: '${{secrets.INJI_ANDROID_RELEASE_STOREPASS}}'
      

      # - name: Upload Artifact to Actions
      #   uses: actions/upload-artifact@v3.1.1
      #   with:
      #     name: Inji
      #     path: android/app/build/outputs/apk/newlogic/debug/
      #     retention-days: 10