name: ID PASS - MOSIP Resident Application

on:
  push:
    branches:
      - main
      - develop
      - demobranch
    tags:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Cache stuff for faster build
      - name: Cache local npm repository
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          path: ~/.npm

      - name: Cache local gradle repository
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper

      - name: Install npm dependencies
        run: |
          npm ci
      - name: Build App Newlogic Release
        run: |
          cd android
          if [ ! -z "$FIREBASE_SECRET" ] && [ -f app/google-services.json.gpg ];then rm -f app/google-services.json;gpg -o app/google-services.json --batch --passphrase="$FIREBASE_SECRET" -d app/google-services.json.gpg;fi
          ./gradlew :app:assembleNewlogicRelease
        env:
          BACKEND_SERVICE_URL: https://api.qa4.mosip.net/residentmobileapp
          FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: android/app/build/outputs/apk/newlogic/release/
          retention-days: 1
