name: Push-Triggers

on:
  push:
    branches:
    - main
    - develop
    - qa-develop
    - 'release-**'
    - ci-publish
  release:
    types: [published]
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
    - main
    - develop
    - qa-develop
    - 'release-**'
    - ci-publish

jobs:
  build-android:
    uses: mosip/kattu/.github/workflows/android-build.yml@master
    with:
      NODE_VERSION: "16.x"
      DEBUG_KEYSTORE_ALIAS: androiddebugkey
    secrets:
      DEBUG_KEYSTORE_PASSWORD: '${{ secrets.INJI_ANDROID_DEBUG_STOREPASS }}'

  build-ios:
    uses: mosip/kattu/.github/workflows/ios-build.yml@master
    with:
      NODE_VERSION: "18.x"

  sonar-check:
    if: ${{ github.event_name != 'pull_request' }}
    uses: mosip/kattu/.github/workflows/sonar.yml@master
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: https://sonarcloud.io
      SONAR_ORGANIZATION: ${{ secrets.ORG_KEY }}
      SLACK_URL: '${{ secrets.SLACK_WEBHOOK }}'
